# Generated by Django 5.0 on 2025-10-20 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('text', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=32, unique=True)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
