# Generated by Django 5.0 on 2025-10-22 16:13

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
