# Generated by Django 5.0 on 2025-10-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_article_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
