# Generated by Django 5.0 on 2025-10-28 12:22

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='embedding',
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding_data', serialize=False, to='scraper.article')),
                ('embedding', pgvector.django.VectorField(dimensions=384)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['embedding'], name='scraper_art_embeddi_0ce1c6_idx')],
            },
        ),
    ]
